pairwin_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, DefaultTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_pairwin
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

simple_pairwin_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, SimpleTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_simple_pairwin
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_pairwin_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-2]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, SimpleTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_simple_pairwin_fold2
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_pairwin_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-3]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, SimpleTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_simple_pairwin_fold3
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_pairwin_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-4]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, SimpleTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_simple_pairwin_fold4
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_pairwin_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-5]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.brawl_stars.model_template, SimpleTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/brawl_stars_simple_pairwin_fold5
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
