m81_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/age_of_empires_ii.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/age_of_empires_ii.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.age_of_empires_ii.torch_model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.age_of_empires_ii.torch_model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/age_of_empires_ii_torch_m81
    bt_model_path: versions/age_of_empires_ii_nrt_torchtf_init/model/model_100.ckpt
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100