breakout:
    environment_name: Breakout
    environment_count: 4
    episode_life: True

breakout-eval:
    environment_name: Breakout
    environment_count: 4
    episode_life: False

breakout-simple-eval:
    environment_id: BreakoutNoFrameskip-v4
    episode_life: False

breakout-16:
    environment_name: Breakout
    environment_count: 16
    episode_life: True

breakout-16-non-episodic:
    environment_name: Breakout
    environment_count: 16
    episode_life: False
