m3_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/rock_paper_scissors_m3
    bt_model_path: versions/rock_paper_scissors_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m9_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/rock_paper_scissors_m9
    bt_model_path: versions/rock_paper_scissors_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m27_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/rock_paper_scissors_m27
    bt_model_path: versions/rock_paper_scissors_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m81_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/rock_paper_scissors_m81
    bt_model_path: versions/rock_paper_scissors_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100