default:
    model_define_path: decision_model.ppo.nn_model.atari.default_model_torch
    use_rnn: False

no_padding:
    model_define_path: decision_model.ppo.nn_model.atari.no_padding_model_torch
    use_rnn: False