fold1_model:
    record: [cgi_drl.default_config, Default, data_storage/match_records/config/rock_paper_scissors.yaml, all]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.rock_paper_scissors.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/rock_paper_scissors_table_m9
    rating_table_model_path: versions/rock_paper_scissors_nrtv3/model
    counter_table_model_path: versions/rock_paper_scissors_m9v3/model
    batch_size: 1024
    start_epoch_number: 1
    end_epoch_number : 1