pairwin_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/league_of_legends.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/league_of_legends.yaml, test-1]
    pairwise_winrate: [cgi_drl.measure_model.pairwise_winrate.config.league_of_legends.model_template, DefaultTemplate, measure_model/pairwise_winrate/config/shared/model.yaml, h128]
    
    version: versions/league_of_legends_pairwin
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
