k3_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-1]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k3]
    
    version: versions/advanced_combination_game_elo_rcc_k3_1
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k3_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-2]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k3]
    
    version: versions/advanced_combination_game_elo_rcc_k3_2
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k3_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-3]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k3]
    
    version: versions/advanced_combination_game_elo_rcc_k3_3
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k3_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-4]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k3]
    
    version: versions/advanced_combination_game_elo_rcc_k3_4
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k3_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-5]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k3]
    
    version: versions/advanced_combination_game_elo_rcc_k3_5
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100

k9_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-1]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k9]
    
    version: versions/advanced_combination_game_elo_rcc_k9_1
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k9_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-2]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k9]
    
    version: versions/advanced_combination_game_elo_rcc_k9_2
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k9_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-3]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k9]
    
    version: versions/advanced_combination_game_elo_rcc_k9_3
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k9_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-4]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k9]
    
    version: versions/advanced_combination_game_elo_rcc_k9_4
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k9_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-5]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k9]
    
    version: versions/advanced_combination_game_elo_rcc_k9_5
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100

k27_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-1]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k27]
    
    version: versions/advanced_combination_game_elo_rcc_k27_1
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k27_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-2]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k27]
    
    version: versions/advanced_combination_game_elo_rcc_k27_2
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k27_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-3]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k27]
    
    version: versions/advanced_combination_game_elo_rcc_k27_3
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k27_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-4]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k27]
    
    version: versions/advanced_combination_game_elo_rcc_k27_4
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k27_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-5]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k27]
    
    version: versions/advanced_combination_game_elo_rcc_k27_5
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100

k81_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-1]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k81]
    
    version: versions/advanced_combination_game_elo_rcc_k81_1
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k81_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-2]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k81]
    
    version: versions/advanced_combination_game_elo_rcc_k81_2
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k81_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-3]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k81]
    
    version: versions/advanced_combination_game_elo_rcc_k81_3
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k81_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-4]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k81]
    
    version: versions/advanced_combination_game_elo_rcc_k81_4
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100
k81_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/advanced_combination_game.yaml, test-5]
    elo_rcc: [cgi_drl.default_config, Default, measure_model/elo_rcc/config/shared/model.yaml, k81]
    
    version: versions/advanced_combination_game_elo_rcc_k81_5
    batch_size: 256
    start_epoch_number: 1
    end_epoch_number : 100