m3_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_m3
    bt_model_path: versions/brawl_stars_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m3_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_simple_m3
    bt_model_path: versions/brawl_stars_simple_nrt_two_hero/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m3_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-2]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_simple_m3_fold2
    bt_model_path: versions/brawl_stars_simple_nrt_fold2/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m3_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-3]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_simple_m3_fold3
    bt_model_path: versions/brawl_stars_simple_nrt_fold3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m3_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-4]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_simple_m3_fold4
    bt_model_path: versions/brawl_stars_simple_nrt_fold4/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m3_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-5]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m3]
    
    version: versions/brawl_stars_simple_m3_fold5
    bt_model_path: versions/brawl_stars_simple_nrt_fold5/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m9_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_m9
    bt_model_path: versions/brawl_stars_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m9_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_simple_m9
    bt_model_path: versions/brawl_stars_simple_nrt_two_hero/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m9_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-2]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_simple_m9_fold2
    bt_model_path: versions/brawl_stars_simple_nrt_fold2/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m9_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-3]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_simple_m9_fold3
    bt_model_path: versions/brawl_stars_simple_nrt_fold3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m9_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-4]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_simple_m9_fold4
    bt_model_path: versions/brawl_stars_simple_nrt_fold4/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m9_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-5]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m9]
    
    version: versions/brawl_stars_simple_m9_fold5
    bt_model_path: versions/brawl_stars_simple_nrt_fold5/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m27_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_m27
    bt_model_path: versions/brawl_stars_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m27_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_simple_m27
    bt_model_path: versions/brawl_stars_simple_nrt_two_hero/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m27_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-2]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_simple_m27_fold2
    bt_model_path: versions/brawl_stars_simple_nrt_fold2/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m27_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-3]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_simple_m27_fold3
    bt_model_path: versions/brawl_stars_simple_nrt_fold3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m27_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-4]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_simple_m27_fold4
    bt_model_path: versions/brawl_stars_simple_nrt_fold4/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m27_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-5]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m27]
    
    version: versions/brawl_stars_simple_m27_fold5
    bt_model_path: versions/brawl_stars_simple_nrt_fold5/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100

m81_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, DefaultTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_m81
    bt_model_path: versions/brawl_stars_nrtv3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m81_1:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-1]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-1]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_simple_m81
    bt_model_path: versions/brawl_stars_simple_nrt_two_hero/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m81_2:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-2]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-2]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_simple_m81_fold2
    bt_model_path: versions/brawl_stars_simple_nrt_fold2/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m81_3:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-3]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-3]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_simple_m81_fold3
    bt_model_path: versions/brawl_stars_simple_nrt_fold3/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m81_4:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-4]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-4]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_simple_m81_fold4
    bt_model_path: versions/brawl_stars_simple_nrt_fold4/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100
simple_m81_5:
    record_train: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, train-5]
    record_test: [cgi_drl.default_config, Default, data_storage/match_records/config/brawl_stars.yaml, test-5]
    nrt: [cgi_drl.measure_model.neural_rating_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_rating_table/config/shared/model.yaml, h128]
    nct: [cgi_drl.measure_model.neural_counter_table.config.brawl_stars.model_template, SimpleTemplate, measure_model/neural_counter_table/config/shared/model.yaml, h128m81]
    
    version: versions/brawl_stars_simple_m81_fold5
    bt_model_path: versions/brawl_stars_simple_nrt_fold5/model
    batch_size: 256
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100