tmlr_playstyle_similarity:
    data_loader: [cgi_drl.default_config, Default, data_storage/demonstration_memory/config/go.yaml, train_9D]
    hsd: [cgi_drl.default_config, Default, representation_model/hsd/config/go/torch_model.yaml, default]
    
    version: versions/go_hsd_default
    update_steps_per_epoch: 1000 # batch size 1024
    is_load_encoder: False
    initial_learning_rate: 0.00025
    start_epoch_number: 1
    end_epoch_number : 100