train-1:
    dataset_path: "~/balance/AdvancedCombinationGame/advanced_combination_game_records_1_train.csv"
test-1:
    dataset_path: "~/balance/AdvancedCombinationGame/advanced_combination_game_records_1_test.csv"

all:
    dataset_path: "~/balance/AdvancedCombinationGame/advanced_combination_game_records.csv"