train-1:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_1_train.csv"
test-1:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_1_test.csv"

train-2:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_2_train.csv"
test-2:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_2_test.csv"

train-3:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_3_train.csv"
test-3:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_3_test.csv"

train-4:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_4_train.csv"
test-4:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_4_test.csv"

train-5:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_5_train.csv"
test-5:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all_5_test.csv"

all:
    dataset_path: "~/balance/AoE2/aoestats_1v1_random_map_elo_all.csv"