train-1:
    dataset_path: "~/balance/RockPaperScissors/rock_paper_scissors_records_1_train.csv"
test-1: 
    dataset_path: "~/balance/RockPaperScissors/rock_paper_scissors_records_1_test.csv"

all: 
    dataset_path: "~/balance/RockPaperScissors/rock_paper_scissors_records.csv"